# Generated by Django 3.0.8 on 2020-07-27 19:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(default='Unknown', null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='video/cover')),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('ongoing', models.BooleanField(default=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'verbose_name_plural': 'VideoUpload',
            },
        ),
        migrations.CreateModel(
            name='UploadVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(blank=True, null=True, upload_to='video/')),
                ('embedvideo', embed_video.fields.EmbedVideoField(blank=True, default='', null=True)),
                ('vdate', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='Anime.VideoUpload')),
            ],
            options={
                'ordering': ('vdate', 'title'),
            },
        ),
        migrations.CreateModel(
            name='UploadAnime',
            fields=[
                ('videoupload_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Anime.VideoUpload')),
                ('foreigns', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='videoss', to='Anime.UploadVideo')),
            ],
            options={
                'verbose_name_plural': 'UploadAnime',
            },
            bases=('Anime.videoupload',),
        ),
    ]
