# Generated by Django 3.0.8 on 2020-08-30 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0003_auto_20200827_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadvideo',
            options={'ordering': ('vdate', 'title', 'pk'), 'verbose_name_plural': 'Upload Videos'},
        ),
        migrations.RemoveField(
            model_name='videoupload',
            name='rated',
        ),
    ]
