# Generated by Django 3.0.8 on 2020-08-30 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='comment',
        ),
    ]
