# Generated by Django 3.0.8 on 2020-09-01 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0007_auto_20200831_0659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='foreign',
        ),
    ]
